# Generated by Django 6.0.6 on 2026-06-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '政治'), ('history', '历史'), ('geography', '地理')], max_length=20, verbose_name='学科'),
        ),
    ]
