# Generated by Django 6.0.6 on 2026-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='附件'),
        ),
    ]
