# Generated by Django 6.0.6 on 2026-06-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_submission_file'),
        ('classes', '0002_alter_classgroup_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='class_group',
        ),
        migrations.AddField(
            model_name='task',
            name='class_groups',
            field=models.ManyToManyField(related_name='tasks', to='classes.classgroup'),
        ),
    ]
